# Generated by Django 2.1.1 on 2019-02-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20190226_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
