# Generated by Django 2.2 on 2019-04-17 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_auto_20190315_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='liked_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
