# Generated by Django 2.1.1 on 2019-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20190417_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_constellation', models.CharField(default='', max_length=50)),
                ('target_constellation', models.CharField(default='', max_length=50)),
                ('path', models.TextField(default='')),
                ('error', models.TextField(default='Всё ок!')),
            ],
        ),
    ]
